using System;
using System.Threading.Tasks;
using GoodDaysApi.Data;
using GoodDaysApi.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GoodDaysApi.Controllers;

[ApiController]
[Route("api/thesis/deadlines")]
public class DeadlinesController : ControllerBase
{
    private readonly AppDbContext _db;
    public DeadlinesController(AppDbContext db) { _db = db; }

    [HttpGet("user/{userId}")]
    public async Task<IActionResult> GetByUser(string userId)
    {
        if (!int.TryParse(userId, out var uid)) return BadRequest("invalid user id");
        var list = await _db.ThesisDeadlines.Where(d => d.UserId == uid).ToListAsync();
        return Ok(list);
    }

    [HttpPost]
    public async Task<IActionResult> Create([FromBody] ThesisDeadline dl)
    {
        // normalize Date to UTC to avoid Npgsql "Kind=Unspecified" errors
        if (dl.Date != null)
            dl.Date = DateTime.SpecifyKind(dl.Date, DateTimeKind.Utc);

        // Id will be auto-generated by the database
        _db.ThesisDeadlines.Add(dl);
        await _db.SaveChangesAsync();
        return Ok(dl);
    }

    [HttpPut("{id}")]
    public async Task<IActionResult> Update(int id, [FromBody] ThesisDeadline body)
    {
        var d = await _db.ThesisDeadlines.FindAsync(id);
        if (d == null) return NotFound();
        d.Title = body.Title;
        // ensure Date is stored as UTC
        if (body.Date != null)
            d.Date = DateTime.SpecifyKind(body.Date, DateTimeKind.Utc);
        else
            d.Date = body.Date;
        d.Completed = body.Completed;
        await _db.SaveChangesAsync();
        return Ok(d);
    }

    [HttpDelete("{id}")]
    public async Task<IActionResult> Delete(int id)
    {
        var d = await _db.ThesisDeadlines.FindAsync(id);
        if (d == null) return NotFound();
        _db.ThesisDeadlines.Remove(d);
        await _db.SaveChangesAsync();
        return Ok();
    }
}
