using System;
using System.Threading.Tasks;
using GoodDaysApi.Data;
using GoodDaysApi.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GoodDaysApi.Controllers;

[ApiController]
[Route("api/thesis/followups")]
public class FollowupsController : ControllerBase
{
    private readonly AppDbContext _db;
    public FollowupsController(AppDbContext db) { _db = db; }

    [HttpGet("patient/{patientId}")]
    public async Task<IActionResult> GetByPatient(int patientId)
    {
        var list = await _db.ThesisFollowups.Where(f => f.PatientId == patientId).ToListAsync();
        return Ok(list);
    }

    [HttpPost]
    public async Task<IActionResult> Create([FromBody] ThesisFollowup f)
    {
        // ensure the followup is linked to an existing patient before we try to save
        if (f.PatientId <= 0 || !await _db.ThesisPatients.AnyAsync(p => p.Id == f.PatientId))
        {
            return BadRequest("Invalid PatientId");
        }

        // Id will be auto-generated by the database
        if (f.VisitDate.HasValue)
            f.VisitDate = DateTime.SpecifyKind(f.VisitDate.Value, DateTimeKind.Utc);
        _db.ThesisFollowups.Add(f);
        await _db.SaveChangesAsync();
        return Ok(f);
    }

    [HttpPut("{id}")]
    public async Task<IActionResult> Update(int id, [FromBody] ThesisFollowup body)
    {
        var f = await _db.ThesisFollowups.FindAsync(id);
        if (f == null) return NotFound();
        f.VisitDate = body.VisitDate;
        if (body.VisitDate.HasValue)
            f.VisitDate = DateTime.SpecifyKind(body.VisitDate.Value, DateTimeKind.Utc);
        f.Status = body.Status;
        f.Notes = body.Notes;
        f.UpdatedAt = DateTime.UtcNow;
        await _db.SaveChangesAsync();
        return Ok(f);
    }

    [HttpDelete("{id}")]
    public async Task<IActionResult> Delete(int id)
    {
        var f = await _db.ThesisFollowups.FindAsync(id);
        if (f == null) return NotFound();
        _db.ThesisFollowups.Remove(f);
        await _db.SaveChangesAsync();
        return Ok();
    }
}
