using System;
using System.Threading.Tasks;
using GoodDaysApi.Data;
using GoodDaysApi.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GoodDaysApi.Controllers;

[ApiController]
[Route("api/thesis/protocol")]
public class ThesisProtocolController : ControllerBase
{
    private readonly AppDbContext _db;
    public ThesisProtocolController(AppDbContext db) { _db = db; }

    [HttpGet("user/{userId}")]
    public async Task<IActionResult> GetByUser(string userId)
    {
        if (!int.TryParse(userId, out var uid)) return BadRequest("invalid user id");
        var p = await _db.ThesisProtocols.FirstOrDefaultAsync(x => x.UserId == uid);
        return Ok(p);
    }

    [HttpPost]
    public async Task<IActionResult> Create([FromBody] ThesisProtocol proto)
    {
        // Id will be auto-generated by the database
        proto.CreatedAt = DateTime.UtcNow;
        _db.ThesisProtocols.Add(proto);
        await _db.SaveChangesAsync();
        return Ok(proto);
    }

    [HttpPut("{id}")]
    public async Task<IActionResult> Update(int id, [FromBody] ThesisProtocol body)
    {
        var p = await _db.ThesisProtocols.FindAsync(id);
        if (p == null) return NotFound();
        // simple mapper for fields
        p.Title = body.Title;
        p.GuideName = body.GuideName;
        p.Department = body.Department;
        p.StudyType = body.StudyType;
        p.StartDate = body.StartDate;
        p.EndDate = body.EndDate;
        p.ProtocolApproved = body.ProtocolApproved;
        p.ApprovalDate = body.ApprovalDate;
        p.IecNumber = body.IecNumber;
        p.SynopsisSubmitted = body.SynopsisSubmitted;
        p.SynopsisApproved = body.SynopsisApproved;
        p.EthicsSubmitted = body.EthicsSubmitted;
        p.EthicsApproved = body.EthicsApproved;
        p.TotalSampleSize = body.TotalSampleSize;
        p.UpdatedAt = DateTime.UtcNow;
        await _db.SaveChangesAsync();
        return Ok(p);
    }
}
