using System;
using System.Threading.Tasks;
using GoodDaysApi.Data;
using GoodDaysApi.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GoodDaysApi.Controllers;

[ApiController]
[Route("api/thesis/protocol")]
public class ThesisProtocolController : ControllerBase
{
    private readonly AppDbContext _db;
    public ThesisProtocolController(AppDbContext db) { _db = db; }

    [HttpGet("user/{userId}")]
    public async Task<IActionResult> GetByUser(string userId)
    {
        if (!int.TryParse(userId, out var uid)) return BadRequest("invalid user id");
        var p = await _db.ThesisProtocols.FirstOrDefaultAsync(x => x.UserId == uid);
        return Ok(p);
    }

    [HttpPost]
    public async Task<IActionResult> Create([FromBody] ThesisProtocol proto)
    {
        // Id will be auto-generated by the database
        proto.CreatedAt = DateTime.UtcNow;
        // UpdatedAt should match CreatedAt initially
        proto.UpdatedAt = DateTime.UtcNow;
        // ensure any incoming dates are marked UTC
        if (proto.StartDate.HasValue)
            proto.StartDate = DateTime.SpecifyKind(proto.StartDate.Value, DateTimeKind.Utc);
        if (proto.EndDate.HasValue)
            proto.EndDate = DateTime.SpecifyKind(proto.EndDate.Value, DateTimeKind.Utc);
        if (proto.ApprovalDate.HasValue)
            proto.ApprovalDate = DateTime.SpecifyKind(proto.ApprovalDate.Value, DateTimeKind.Utc);
        _db.ThesisProtocols.Add(proto);
        await _db.SaveChangesAsync();
        return Ok(proto);
    }

    [HttpPut("{id}")]
    public async Task<IActionResult> Update(int id, [FromBody] ThesisProtocol body)
    {
        var p = await _db.ThesisProtocols.FindAsync(id);
        if (p == null) return NotFound();
        // simple mapper for fields
        p.Title = body.Title;
        p.GuideName = body.GuideName;
        p.Department = body.Department;
        p.College = body.College;
        p.StudyType = body.StudyType;
        p.Objective = body.Objective;
        p.InclusionCriteria = body.InclusionCriteria;
        p.ExclusionCriteria = body.ExclusionCriteria;
        p.StudyDuration = body.StudyDuration;
        p.StudyGroups = body.StudyGroups;
        p.TotalFollowups = body.TotalFollowups;
        // convert any dates to UTC Kind
        if (body.StartDate.HasValue)
            p.StartDate = DateTime.SpecifyKind(body.StartDate.Value, DateTimeKind.Utc);
        else
            p.StartDate = null;
        if (body.EndDate.HasValue)
            p.EndDate = DateTime.SpecifyKind(body.EndDate.Value, DateTimeKind.Utc);
        else
            p.EndDate = null;
        p.ProtocolApproved = body.ProtocolApproved;
        if (body.ApprovalDate.HasValue)
            p.ApprovalDate = DateTime.SpecifyKind(body.ApprovalDate.Value, DateTimeKind.Utc);
        else
            p.ApprovalDate = null;
        p.IecNumber = body.IecNumber;
        p.SynopsisSubmitted = body.SynopsisSubmitted;
        p.SynopsisApproved = body.SynopsisApproved;
        p.EthicsSubmitted = body.EthicsSubmitted;
        p.EthicsApproved = body.EthicsApproved;
        p.TotalSampleSize = body.TotalSampleSize;
        p.UpdatedAt = DateTime.UtcNow;
        await _db.SaveChangesAsync();
        return Ok(p);
    }
}
